# Generated by Django 5.2.6 on 2025-09-11 02:32

import django.db.models.deletion
import localflavor.br.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('max_pausas_diarias', models.PositiveIntegerField(default=2, help_text='Número máximo de pausas curtas (ex: café) permitidas por dia.')),
                ('duracao_max_pausas_minutos', models.PositiveIntegerField(default=20, help_text='Duração total máxima de todas as pausas somadas, em minutos.')),
                ('cbo', models.CharField(blank=True, max_length=10, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CentroDeCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('deve_alterar_senha', models.BooleanField(default=True)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro'), ('N', 'Prefiro não dizer')], max_length=1)),
                ('telefone_celular', models.CharField(blank=True, max_length=20, null=True)),
                ('email_pessoal', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('escolaridade', models.CharField(blank=True, choices=[('EF', 'Ensino Fundamental'), ('EM', 'Ensino Médio'), ('SI', 'Superior Incompleto'), ('SC', 'Superior Completo'), ('PG', 'Pós-Graduação')], max_length=2, null=True)),
                ('contato_emergencia_nome', models.CharField(blank=True, max_length=255, null=True)),
                ('contato_emergencia_telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('data_contratacao', models.DateField()),
                ('data_demissao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('FERIAS', 'Férias'), ('AFASTADO', 'Afastado'), ('DESLIGADO', 'Desligado')], default='ATIVO', max_length=10)),
                ('status_operacional', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('EM_PAUSA', 'Em Pausa'), ('OFFLINE', 'Offline')], default='OFFLINE', max_length=20)),
                ('cep', models.CharField(max_length=9)),
                ('rua', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=20)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('cpf', localflavor.br.models.BRCPFField(max_length=14, unique=True)),
                ('rg', models.CharField(max_length=12)),
                ('agencia', models.CharField(max_length=10)),
                ('conta', models.CharField(max_length=15)),
                ('banco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionarios.banco')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionarios.cargo')),
                ('centro_de_custo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionarios.centrodecusto')),
                ('supervisor', models.ForeignKey(blank=True, help_text='O supervisor direto deste funcionário.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipe', to='funcionarios.funcionario')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA_PAUSA', 'Saída para Pausa'), ('VOLTA_PAUSA', 'Volta da Pausa'), ('SAIDA_ALMOCO', 'Saída Almoço'), ('VOLTA_ALMOCO', 'Volta Almoço'), ('SAIDA', 'Saída')], max_length=20)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_ponto', to='funcionarios.funcionario')),
            ],
            options={
                'verbose_name': 'Registro de Ponto',
                'verbose_name_plural': 'Registros de Ponto',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoAlteracaoBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia', models.CharField(max_length=10)),
                ('conta', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('A', 'Aprovado'), ('R', 'Recusado')], default='P', max_length=1)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('banco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionarios.banco')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoAlteracaoEndereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=9)),
                ('rua', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=20)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('A', 'Aprovado'), ('R', 'Recusado')], default='P', max_length=1)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.funcionario')),
            ],
        ),
    ]
