# Generated by Django 5.2.6 on 2025-09-11 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='cbo',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='duracao_max_pausas_minutos',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='max_pausas_diarias',
        ),
        migrations.CreateModel(
            name='RegraDePausa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Pausa Café 1', max_length=100)),
                ('ordem', models.PositiveIntegerField(help_text='A ordem em que a pausa deve ser tirada (1 para a primeira, 2 para a segunda, etc.)')),
                ('duracao_minutos', models.PositiveIntegerField(help_text='A duração desta pausa específica em minutos.')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras_de_pausa', to='funcionarios.cargo')),
            ],
            options={
                'verbose_name': 'Regra de Pausa',
                'verbose_name_plural': 'Regras de Pausa',
                'ordering': ['cargo', 'ordem'],
                'unique_together': {('cargo', 'ordem')},
            },
        ),
    ]
