# Generated by Django 5.2.6 on 2025-09-07 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_funcionario_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='telefone',
        ),
    ]
