# Generated by Django 5.2.6 on 2025-09-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_remove_cargo_cbo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='cbo',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
