# Generated by Django 5.2.6 on 2025-09-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_remove_funcionario_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='deve_alterar_senha',
            field=models.BooleanField(default=True),
        ),
    ]
