# Generated by Django 5.2.6 on 2025-09-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_cargo_cbo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='cbo',
            field=models.CharField(blank=True, help_text='Digite o código CBO (ex: 4223-10) e saia do campo.', max_length=10, null=True, unique=True),
        ),
    ]
