# Generated by Django 5.2.6 on 2025-09-09 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0004_funcionario_deve_alterar_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='contato_emergencia_nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='contato_emergencia_telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='data_contratacao',
            field=models.DateField(default=datetime.date(2025, 9, 9)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='data_demissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='email_pessoal',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='escolaridade',
            field=models.CharField(blank=True, choices=[('EF', 'Ensino Fundamental'), ('EM', 'Ensino Médio'), ('SI', 'Superior Incompleto'), ('SC', 'Superior Completo'), ('PG', 'Pós-Graduação')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('FERIAS', 'Férias'), ('AFASTADO', 'Afastado'), ('DESLIGADO', 'Desligado')], default='ATIVO', max_length=10),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='telefone_celular',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
