# Generated by Django 5.2.6 on 2025-09-11 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0004_alter_cargo_cbo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Seg-Sáb 08:00-14:20', max_length=100, unique=True)),
                ('dias_semana', models.CharField(help_text='Dias da semana separados por vírgula (0=Seg, 1=Ter, ..., 6=Dom).', max_length=15)),
                ('horario_entrada', models.TimeField()),
                ('horario_saida', models.TimeField()),
                ('duracao_almoco_minutos', models.PositiveIntegerField(default=60, help_text='Duração do intervalo de almoço padrão em minutos.')),
            ],
            options={
                'verbose_name': 'Escala de Trabalho',
                'verbose_name_plural': 'Escalas de Trabalho',
            },
        ),
        migrations.CreateModel(
            name='BancoDeHoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('minutos', models.IntegerField(help_text='Minutos a serem creditados (positivo) ou debitados (negativo).')),
                ('descricao', models.CharField(help_text='Ex: Horas extras, Atraso, Saída antecipada.', max_length=255)),
                ('processado_em', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banco_de_horas', to='funcionarios.funcionario')),
            ],
            options={
                'verbose_name': 'Registro de Banco de Horas',
                'verbose_name_plural': 'Registros de Banco de Horas',
                'ordering': ['-data'],
            },
        ),
        migrations.AddField(
            model_name='cargo',
            name='escala_padrao',
            field=models.ForeignKey(blank=True, help_text='A escala padrão para novos funcionários neste cargo.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionarios.escala'),
        ),
        migrations.CreateModel(
            name='FuncionarioEscala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, help_text='Deixe em branco se for a escala atual/permanente.', null=True)),
                ('escala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='funcionarios.escala')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to='funcionarios.funcionario')),
            ],
            options={
                'verbose_name': 'Escala do Funcionário',
                'verbose_name_plural': 'Escalas dos Funcionários',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
