# Generated by Django 5.2.6 on 2025-09-12 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0005_escala_bancodehoras_cargo_escala_padrao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_ponto', models.DateTimeField(help_text='Data e hora em que o funcionário deseja registrar o ponto.')),
                ('motivo', models.TextField(max_length=500)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado')], default='PENDENTE', max_length=10)),
                ('data_analise', models.DateTimeField(blank=True, null=True)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('analisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_horario_analisadas', to='funcionarios.funcionario')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_horario', to='funcionarios.funcionario')),
            ],
            options={
                'verbose_name': 'Solicitação de Ponto Fora de Hora',
                'verbose_name_plural': 'Solicitações de Ponto Fora de Hora',
                'ordering': ['-data_solicitacao'],
            },
        ),
    ]
