# Generated by Django 5.2.6 on 2025-09-14 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0006_solicitacaohorario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroponto',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('SAIDA_PAUSA', 'Saída para Pausa Programada'), ('VOLTA_PAUSA', 'Volta da Pausa Programada'), ('SAIDA_PAUSA_PESSOAL', 'Saída para Pausa Pessoal'), ('VOLTA_PAUSA_PESSOAL', 'Volta da Pausa Pessoal'), ('SAIDA_ALMOCO', 'Saída Almoço'), ('VOLTA_ALMOCO', 'Volta Almoço')], max_length=30),
        ),
        migrations.CreateModel(
            name='SolicitacaoAbono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_abono', models.CharField(choices=[('FALTA', 'Abono de Falta'), ('ATRASO', 'Abono de Atraso/Horas')], max_length=10)),
                ('data_inicio', models.DateTimeField(help_text='Data e hora de início do período a ser abonado')),
                ('data_fim', models.DateTimeField(help_text='Data e hora de fim do período a ser abonado')),
                ('motivo', models.TextField(max_length=500)),
                ('documento', models.FileField(blank=True, null=True, upload_to='documentos_abono/')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado')], default='PENDENTE', max_length=10)),
                ('data_analise', models.DateTimeField(blank=True, null=True)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('analisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_abono_analisadas', to='funcionarios.funcionario')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_abono', to='funcionarios.funcionario')),
            ],
            options={
                'verbose_name': 'Solicitação de Abono',
                'verbose_name_plural': 'Solicitações de Abono',
                'ordering': ['-data_solicitacao'],
            },
        ),
    ]
