# Generated by Django 5.2.6 on 2025-09-09 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0005_funcionario_contato_emergencia_nome_and_more'),
        ('funcionarios', '0006_popular_cargos_iniciais'),
    ]

    operations = [
    ]
