# Generated by Django 5.2.6 on 2025-09-09 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0007_merge_20250909_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipe', to='funcionarios.funcionario'),
        ),
    ]
