# Generated by Django 5.2.8 on 2025-11-18 13:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0007_alter_registroponto_tipo_solicitacaoabono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroponto',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data e Hora'),
        ),
    ]
