# Generated by Django 5.2.6 on 2024-05-23 12:00

from django.db import migrations

def criar_grupo_analista_rh(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    # Cria o grupo
    analista_rh_group, created = Group.objects.get_or_create(name='Analista de RH')

    if created:
        # Define os modelos que o Analista de RH deve gerenciar
        modelos_rh = [
            'funcionario', 
            'registroponto', 
            'bancodehoras', 
            'escala', 
            'funcionarioescala',
            'solicitacaoabono',
            'solicitacaohorario',
        ]
        
        # Encontra o content type para os modelos
        content_types = ContentType.objects.filter(
            app_label='funcionarios',
            model__in=modelos_rh
        )
        
        # Pega todas as permissões para esses modelos (add, change, delete, view)
        permissions = Permission.objects.filter(content_type__in=content_types)
        
        analista_rh_group.permissions.set(permissions)
        print("Grupo 'Analista de RH' criado e permissões atribuídas com sucesso.")

def remover_grupo_analista_rh(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name='Analista de RH').delete()
    print("Grupo 'Analista de RH' removido.")


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0008_alter_registroponto_timestamp'),
    ]

    operations = [
        migrations.RunPython(criar_grupo_analista_rh, remover_grupo_analista_rh),
    ]