# Generated by Django 5.2.6 on 2025-09-09 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0008_funcionario_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='O supervisor direto deste funcionário.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipe', to='funcionarios.funcionario'),
        ),
    ]
