# Generated by Django 5.2.6 on 2025-09-09 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0009_alter_funcionario_supervisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA_ALMOCO', 'Saída Almoço'), ('VOLTA_ALMOCO', 'Volta Almoço'), ('SAIDA', 'Saída')], max_length=20)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_ponto', to='funcionarios.funcionario')),
            ],
            options={
                'verbose_name': 'Registro de Ponto',
                'verbose_name_plural': 'Registros de Ponto',
                'ordering': ['-timestamp'],
            },
        ),
    ]
