# Generated by Django 5.2.6 on 2024-05-23 15:00

from django.db import migrations, models

def remover_duplicatas(apps, schema_editor):
    """
    Encontra e remove registros duplicados de BancoDeHoras para a mesma combinação
    de funcionário e data, mantendo apenas o registro mais recente.
    """
    BancoDeHoras = apps.get_model('funcionarios', 'BancoDeHoras')
    db_alias = schema_editor.connection.alias

    # Encontra as combinações de funcionário e data que são duplicadas
    duplicates = (
        BancoDeHoras.objects.using(db_alias)
        .values('funcionario', 'data')
        .annotate(count_id=models.Count('id'))
        .filter(count_id__gt=1)
    )

    print(f"\nEncontradas {len(duplicates)} combinações de (funcionário, data) duplicadas. Limpando...")

    # Para cada combinação duplicada, mantém o registro mais recente e deleta os outros
    for item in duplicates:
        # Pega todos os registros para esta combinação, ordenados do mais novo para o mais antigo
        registros = BancoDeHoras.objects.using(db_alias).filter(
            funcionario=item['funcionario'],
            data=item['data']
        ).order_by('-processado_em')
        
        # O primeiro é o que queremos manter
        registro_a_manter = registros.first()
        
        # Monta uma lista de IDs para deletar (todos exceto o que queremos manter)
        ids_a_deletar = list(registros.exclude(pk=registro_a_manter.pk).values_list('id', flat=True))
        
        if ids_a_deletar:
            print(f"  - Deletando {len(ids_a_deletar)} registro(s) duplicado(s) para func_id={item['funcionario']}, data={item['data']}")
            BancoDeHoras.objects.using(db_alias).filter(pk__in=ids_a_deletar).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0009_criar_grupo_analista_rh'),
    ]

    operations = [
        migrations.RunPython(remover_duplicatas, migrations.RunPython.noop),
    ]