# Generated by Django 5.2.6 on 2025-09-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0010_registroponto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='duracao_max_pausas_minutos',
            field=models.PositiveIntegerField(default=20, help_text='Duração total máxima de todas as pausas somadas, em minutos.'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='max_pausas_diarias',
            field=models.PositiveIntegerField(default=2, help_text='Número máximo de pausas curtas (ex: café) permitidas por dia.'),
        ),
        migrations.AlterField(
            model_name='registroponto',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA_PAUSA', 'Saída para Pausa'), ('VOLTA_PAUSA', 'Volta da Pausa'), ('SAIDA_ALMOCO', 'Saída Almoço'), ('VOLTA_ALMOCO', 'Volta Almoço'), ('SAIDA', 'Saída')], max_length=20),
        ),
    ]
