# Generated by Django 5.2.8 on 2025-11-19 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0010_limpar_duplicados_bancohoras'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bancodehoras',
            unique_together={('funcionario', 'data')},
        ),
    ]
