# Generated by Django 5.2.8 on 2025-11-21 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0011_alter_bancodehoras_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data', models.DateField(unique=True)),
                ('recorrente', models.BooleanField(default=False, help_text='Marque se for um feriado que se repete anualmente (ex: Natal). O ano da data será ignorado.')),
            ],
        ),
        migrations.AddField(
            model_name='escala',
            name='prioritaria',
            field=models.BooleanField(default=False, verbose_name='Escala Prioritária (Trabalha em Feriados)'),
        ),
    ]
